name: CI

on:
  push:

jobs:
  test:
    name: Run test commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm i

      - name: Test 'version' command
        run: npm run test-version

      - name: Test 'help' command
        run: npm run test-help

      - name: Test 'png' command
        run: npm run test-png

      - name: Test 'gif' command
        run: npm run test-gif

      - name: Test 'mp4' command
        run: npm run test-mp4
